name: Test Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Cambia a tu versión de Go

      - name: Ejecutar pruebas con cobertura
        run: go test -coverprofile=coverage.out ./...

      - name: Verificar cobertura mínima (90%)
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Coverage actual: $coverage%"
          if (( $(echo "$coverage < 90" | bc -l) )); then
            echo "❌ El coverage es menor al 90%. No puedes hacer merge."
            exit 1
          else
            echo "✅ El coverage es suficiente."
          fi

