name: "Go Coverage"

on:
  pull_request:
  push:
    branches:
      - main  # Asegura que se ejecute en la rama principal

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10  # Necesario para encontrar notas previas de cobertura

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable  # Usa la versión estable de Go

      - name: Debug GH Token
        run: echo "GH_TOKEN is set"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive Go Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage-report
          path: ${{ steps.coverage.outputs.report-pathname }}

      - name: Debug working directory
        run: ls -la  # Verificar en qué directorio estamos
